### ISSUE TITLE
极验没有社区论坛吗？

### ISSUE THREAD

**Issue by blackchena** [GeeTeam/gt3-ios-sdk#10]
想问下二次认证用了`-(BOOL)shouldUseDefaultSecondaryValidate` 为NO
 `- (void)gtCaptcha:(GT3CaptchaManager *)manager didReceiveCaptchaCode:(NSString *)code result:(NSDictionary *)result message:(NSString *)message;` 
还需要实现这个
`-(void) response:(NSURLResponse *)response error:(GT3Error *)error decisionHandler:(void (^)(GT3SecondaryCaptchaPolicy captchaPolicy))decisionHandler;`
 吗？

**Comment by blackchena** [comment]
如果不适用默认API2请求逻辑，如何在请求成功或者失败的情况下更新验证视图，像decisionHandler(GT3SecondaryCaptchaPolicyAllow)或者decisionHandler(GT3SecondaryCaptchaPolicyForbidden)那样？

**Comment by joohs** [comment]
没有找到你的这个方法呀
-(void) response:(NSURLResponse *)response error:(GT3Error *)error decisionHandler:(void (^)(GT3SecondaryCaptchaPolicy captchaPolicy))decisionHandler。
很类似的只有这个方法
- (void)gtCaptcha:(GT3CaptchaManager *)manager didReceiveSecondaryCaptchaData:(NSData *)data response:(NSURLResponse *)response error:(GT3Error *)error decisionHandler:(void (^)(GT3SecondaryCaptchaPolicy))decisionHandler {
    DLog(@"该方法不会调用，实现这个方法只是因为这个代理方法是@required");
}
如果你说的是这个方法，那么推荐你实现它，不实现的话会出现一个警告

**Comment by NikoXu** [comment]
@joohs 上一版本的bitcode编译有一些问题, 我们刚刚做了更新。

请重新下载使用。

**Comment by joohs** [comment]
@NikoXu  已经可以使用bitcode了，非常感谢

**Comment by NikoXu** [comment]
@blackchena 
`-(BOOL)shouldUseDefaultSecondaryValidate:`为`NO
 `后, `-(void) response:(NSURLResponse *)response error:(GT3Error *)error decisionHandler:(void (^)(GT3SecondaryCaptchaPolicy captchaPolicy))decisionHandler`不会被调用。

根据您的需求, 推荐方案是: 
`-(BOOL)shouldUseDefaultSecondaryValidate:`为`YES`
然后通过
`- (void)gtCaptcha:(GT3CaptchaManager *)manager willSendSecondaryCaptchaRequest:(NSURLRequest *)originalRequest withReplacedRequest:(void (^)(NSMutableURLRequest * request))replacedRequest;`来修改secondaryCaptchaRequest
该回调会返回`originalRequest`， 这里可以对`originalRequest`操作完后, 用`replacedRequest`block返回修改后的request对象。

**Comment by NikoXu** [comment]
关于"社区"问题, 我们之前尝试过, 但是效果并不理想。

我们推荐的是方式是通过双方的商务沟通后再提供支持。

通过issues提供反馈明确的问题, 我们也会给予回复的。
