### ISSUE TITLE
添加入pod之后报错.  +[NSBundle gt3_resourcesBundle]: unrecognized selector sent to class 0x106f6dbb8

### ISSUE THREAD

**Issue by Akateason** [GeeTeam/gt3-ios-sdk#15]
添加入pod之后报错.  
+[NSBundle gt3_resourcesBundle]: unrecognized selector sent to class 0x106f6dbb8

**Comment by ddddxxx** [comment]
需要在 `Other Linker Flags` 中添加 `-ObjC` 和 `-all_load`。详见官网文档: https://docs.geetest.com/install/deploy/client/ios#导入SDK

**Comment by Akateason** [comment]
可能你理解有问题, 我的意思是,将这个库所有打包进入一个pod中. +[NSBundle gt3_resourcesBundle]:这个错误明显是你调用图片或其他资源时, 没有用到bundleForClass. 导致找不到pod中的bundle

**Comment by Akateason** [comment]
你可以动手试试, 我在podspec加了allload, objc完全不行.  还是要额外手动拖入两个库.
或者官方提供下pod.

**Comment by ddddxxx** [comment]
请再详细描述一下问题和复现步骤，以及podspec文件。如果我没理解错的话，通过pod添加的库会崩溃，额外手动拖入就不会？

**Comment by Akateason** [comment]
因为官方没有提供pod的方式, 必须手动加入. 接入很不方便. 
所以我在自己弄个pod引入你们的库. 
说白了,你可以试下实现pod给外部接入的方式.
