### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by Serena1993** [GeeTeam/gt3-ios-sdk#16]
提审后被拒绝
TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

 项目目录下 grep -r UIWebView . 
提示 /Frameworks/GT3Captcha.framework/GT3Captcha matches

麻烦请问 /GT3Captcha.framework/ 是否包含UIWebView API？

感谢

**Comment by NikoXu** [comment]
@Serena1993  感谢您的反馈🙏

这个 Demo 仓库我们放弃维护已经快三年了。
* 依赖方式获取：获取最新的 SDK 可以在 `Podfile` 中添加 `pod 'GT3Captcha-iOS'`后，调用 `pod install` 获取最新的 SDK。
* 手动方式获取：通过 [下载页面](https://docs.geetest.com/sensebot/deploy/client/ios#安装) 获取最新的 SDK。

部署说明可以参考 [安装说明](https://docs.geetest.com/sensebot/deploy/client/ios#安装)。
