### ISSUE TITLE
master分支的回调方法没有走

### ISSUE THREAD

**Issue by zerorrr** [GeeTeam/gt3-ios-sdk#3]
测试demo也没有回调，是配置问题还是什么问题

- (void)gtCaptcha:(GT3CaptchaManager *)manager didReceiveSecondaryCaptchaData:(NSData *)data response:(NSURLResponse *)response error:(GT3Error *)error decisionHandler:(void (^)(GT3SecondaryCaptchaPolicy))decisionHandler {
    if (!error) {
        //处理你的验证结果
        NSLog(@"\nsession ID: %@,\ndata: %@", [manager getCookieValue:@"msid"], [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
        //成功请调用decisionHandler(GT3SecondaryCaptchaPolicyAllow)
        decisionHandler(GT3SecondaryCaptchaPolicyAllow);
        //失败请调用decisionHandler(GT3SecondaryCaptchaPolicyForbidden)
        //decisionHandler(GT3SecondaryCaptchaPolicyForbidden);
    }
    else {
        //二次验证发生错误
        decisionHandler(GT3SecondaryCaptchaPolicyForbidden);
        NSLog(@"validate error: %ld, %@", (long)error.code, error.localizedDescription);
    }
}

**Comment by NikoXu** [comment]
@zerorrr 请先使用 develop分支上的, 我们还没合并上去。 master是2个月之前不小心提交上去的。

**Comment by zerorrr** [comment]
@NikoXu  dev分支好像没有button模式啊  如何设置成button模式呀
