### ISSUE TITLE
希望添加pod支持

### ISSUE THREAD

**Issue by zjw7sky** [GeeTeam/gt3-ios-sdk#7]
希望添加pod支持，方便引用

**Comment by Changzw** [comment]
+1

**Comment by Akateason** [comment]
+1

**Comment by NikoXu** [comment]
* 依赖方式获取：获取最新的 SDK 可以在 `Podfile` 中添加 `pod 'GT3Captcha-iOS'`后，调用 `pod install` 获取最新的 SDK。
* 手动方式获取：通过 [下载页面](https://docs.geetest.com/sensebot/deploy/client/ios#安装) 获取最新的 SDK。
