### ISSUE TITLE
为什么我使用bitcode的sdk，还是只能关闭bitcode才可以编译成功？

### ISSUE THREAD

**Issue by joohs** [GeeTeam/gt3-ios-sdk#9]
使用bitcode文件夹下的sdk，替换了demo里面的sdk，把Enable Bitcode设置为YES,编译不通过，提示
GT3Captcha.framework/GT3Captcha(GT3ActivityIndicatorView.o)' does not contain bitcode. 

是我操作的姿势不正确吗？

**Comment by NikoXu** [comment]
上一版本的bitcode编译有一些问题, 我们刚刚做了更新。

请重新下载使用。

**Comment by joohs** [comment]
嗯嗯，已经可以用了，非常感谢
